// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUYU8h-5Zm_r52d-BnMIMKk9tTwIiDmjE',
    appId: '1:214187715709:web:0282fa2ccc7dce44d09514',
    messagingSenderId: '214187715709',
    projectId: 'pizza-delivery-8d755',
    authDomain: 'pizza-delivery-8d755.firebaseapp.com',
    storageBucket: 'pizza-delivery-8d755.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjTxdxpQgdqrDgefC5l6VX1xqIl_pvYqM',
    appId: '1:214187715709:android:00df7655832015c2d09514',
    messagingSenderId: '214187715709',
    projectId: 'pizza-delivery-8d755',
    storageBucket: 'pizza-delivery-8d755.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0FDqLB7V0rCy_QdEHv9fsNXpECT5CXJY',
    appId: '1:214187715709:ios:b236a12a21acd0a5d09514',
    messagingSenderId: '214187715709',
    projectId: 'pizza-delivery-8d755',
    storageBucket: 'pizza-delivery-8d755.appspot.com',
    iosBundleId: 'com.example.projectManagementApp',
  );
}
